# Generated by Django 3.2.5 on 2021-07-06 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menudog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
